blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://powersemmi.github.io/ruststream-sqlx/
    about: The ruststream-sqlx documentation - check here before opening an issue.
